apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: todo-api-secrets
      type: Opaque
      data:
        - objectName: db-server
          key: DB_SERVER
        - objectName: db-name
          key: DB_NAME
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<key_vault_secrets_provider_client_id>"
    keyvaultName: "todo-api-secrets"
    objects: |
      array:
        - |
          objectName: db-server
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
    tenantId: "<your-tenant-id>"
